name: CI Additional
on:
  workflow_dispatch: # allows you to trigger manually
  schedule:
    - cron: "0 0 1 */3 *" # Run every 3 months

jobs:
  min-version-policy:
    name: Minimum Version Policy
    runs-on: "ubuntu-latest"
    env:
      POLICY_FILE: .github/ci/policy.yaml
      ENVIRONMENTS: "pixi:test-minimum"
      MANIFEST_PATH: ./pixi.toml
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - uses: xarray-contrib/minimum-dependency-versions@v1.0.0
        with:
          policy: $${{ env.POLICY_FILE }}
          environments: |
            $${{ env.ENVIRONMENTS }}
          manifest-path: $${{ env.MANIFEST_PATH }}

  linkcheck:
    name: pixi run docs-linkcheck
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi run docs-linkcheck
