name: CI Additional
on:
  workflow_dispatch: # allows you to trigger manually
  schedule:
    - cron: "0 0 1 */3 *" # Run every 3 months

jobs:
  min-version-policy:
    name: Minimum Version Policy
    runs-on: "ubuntu-latest"
    env:
      COLUMNS: 120
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - run: |
          uvx --from xarray-minimum-dependency-policy==2.0.0 \
          minimum-versions validate \
          --policy=.github/ci/policy.yaml \
          --manifest-path=./pixi.toml \
          pixi:test-minimum

  linkcheck:
    name: pixi run docs-linkcheck
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi run docs-linkcheck
