name: CI Additional
on:
  workflow_dispatch: # allows you to trigger manually
  schedule:
    - cron: "0 0 1 */3 *" # Run every 3 months

jobs:
  min-version-policy:
    name: Minimum Version Policy
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - uses: xarray-contrib/minimum-dependency-versions@v1.0.0
        with:
          policy: .github/ci/policy.yaml
          environments: |
            pixi:test-minimum
          manifest-path: ./pixi.toml # or pyproject.toml

  linkcheck:
    name: pixi run docs-linkcheck
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi run docs-linkcheck
